version: '3.5'

services:
  proxy_pool:
    build: .
    ports:
      - "5010:5010"
    networks:
      - proxy_tool
    environment:
      db_type: REDIS
      ssdb_host: proxy_redis
      ssdb_port: 6379
  proxy_redis:
    image: "redis"
    networks:
      - proxy_tool

networks:
  proxy_tool:
    name: proxy_tool
